// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcoeN5CDizl63FNV7apdIrHhEcdcpcDoE',
    appId: '1:1051048633429:android:5366329eaf0e2c58e860dc',
    messagingSenderId: '1051048633429',
    projectId: 'near-hood',
    storageBucket: 'near-hood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6tNg73WlxAUeTJktrLd3_2i1KUFqShRU',
    appId: '1:1051048633429:ios:c390db26726fe3f4e860dc',
    messagingSenderId: '1051048633429',
    projectId: 'near-hood',
    storageBucket: 'near-hood.firebasestorage.app',
    iosBundleId: 'com.harsh.nearhood',
  );
}
